Add "svelte" entry point to package.json
Without it, when using SvelteKit, and doing the following import:

```javascript
import { portal } from "svelte-portal"
```

I get this error:

```
/home/cbenz/Dev/tests/my-project/node_modules/svelte-portal/src/Portal.svelte:1
<script context="module">
^

SyntaxError: Unexpected token '<'
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/home/cbenz/Dev/tests/my-project/node_modules/svelte-portal/src/main.cjs.js:1:18)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
```